version: "3.9"

services:
  fwa-monitor:
    image: ghcr.io/paulbertoli94/b818-monitor:latest
    container_name: fwa-monitor
    environment:
      ROUTER_HOST: "192.168.8.1"
      ROUTER_USER: ""
      ROUTER_PASSWORD: ""
      POLL_SECONDS: "1"
    ports:
      - "8088:8088"
    restart: unless-stopped
